apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd

  annotations:
    # REQUIRED FORMAT (THIS IS THE FIX)
    argocd-image-updater.argoproj.io/image-list: app=docker.io/sumonaust/python-app:*

    # container name inside Deployment
    argocd-image-updater.argoproj.io/app.container: python-app

    # update strategy
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build

    # git write-back
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main

    # optional safety filter
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^([a-f0-9]{7,40})$

spec:
  project: default

  source:
    repoURL: https://github.com/sumonaust/GitOps-Image-Updater.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: python-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true