apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd

  annotations:
    # IMPORTANT: alias mapping (required for Image Updater detection)
    argocd-image-updater.argoproj.io/image-list: app=docker.io/sumonaust/python-app

    # Git write-back settings
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main

    # Use newest build (good for SHA tags like b693f27)
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build

    # Only allow SHA-like tags (optional but recommended)
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^([a-f0-9]{7,40})$

spec:
  project: default

  source:
    repoURL: https://github.com/sumonaust/GitOps-Image-Updater.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: python-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true