apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: app=docker.io/sumonaust/python-app

    # IMPORTANT: use semver or newest-build strategy for SHA tags
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
    
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^([a-f0-9]{7,40})$

    # write updated SHA back to Git
    argocd-image-updater.argoproj.io/write-back-method: git

    # ensure it commits updated SHA
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: default

  source:
    repoURL: https://github.com/sumonaust/GitOps-Image-Updater.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: python-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
